# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LmnnuMq4opuNzqcNY2eu_69y0ArYEbe9
"""

nu1 = int(input('quer tabuada de qual numero'))
inicio = int(input(' inicio'));
fim = int(input(' fim'));

if inicio < fim:
  for i in range(inicio,fim +1):
    print(nu1*i)
elif inicio > fim:
  for i in range(inicio,fim, -1):
    print(nu1*i)